name: 'Release Container GHCR'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/Release_Alist_tvbox_images.yml'
      - 'HomeAssistant-Add-ons/alist-tvbox/app_version'
  schedule:
    - cron: '0 */6 * * *'  # 每12小时运行一次

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set app version
        run: |
            version=$(cat HomeAssistant-Add-ons/alist-tvbox/app_version)
            echo "APP_VERSION=$version" >> $GITHUB_ENV
            # 获取远程版本（忽略 curl 错误，失败时版本为app_version）
            REMOTE_VERSION=$(curl -fsSL http://d.har01d.cn/app_version | head -n 1 || echo ${{ env.APP_VERSION }})
            # 对比本地和远程版本
            if [ "$REMOTE_VERSION" != "${{ env.APP_VERSION }}" ]; then
              echo "New version detected: $REMOTE_VERSION"
              echo "APP_VERSION=$REMOTE_VERSION" >> $GITHUB_ENV
              rm HomeAssistant-Add-ons/alist-tvbox/app_version
              touch HomeAssistant-Add-ons/alist-tvbox/app_version
              echo $REMOTE_VERSION > HomeAssistant-Add-ons/alist-tvbox/app_version
              echo "changed=true" >> $GITHUB_OUTPUT
              # 提交版本更新
              git config --local user.name "github-actions[bot]"
              git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add HomeAssistant-Add-ons/alist-tvbox/app_version
              git commit -m "Update app_version to $REMOTE_VERSION"
              git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
            else
              echo "Version unchanged: ${{ env.APP_VERSION }}"
              echo "changed=false" >> $GITHUG_OUTPUT
            fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.check-version.outputs.changed == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.check-version.outputs.changed == 'true'

      - name: Login to GitHub Container Registry (ghcr)
        uses: docker/login-action@v2
        if: steps.check-version.outputs.changed == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.HASS_TOKEN }}

      - name: Build Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        if: steps.check-version.outputs.changed == 'true'
        with:
          context: .
          file: HomeAssistant-Add-ons/alist-tvbox/Dockerfile-xiaoya
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:latest,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:${{ env.APP_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Build host mode Docker and push to ghcr
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     file: HomeAssistant-Add-ons/alist-tvbox/Dockerfile-host
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:hostmode,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:hostmode-${{ env.APP_VERSION}}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Build standalone Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        if: steps.check-version.outputs.changed == 'true'
        with:
          context: .
          file: HomeAssistant-Add-ons/alist-tvbox/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alist-tvbox:latest,ghcr.io/${{ github.repository_owner }}/alist-tvbox:${{ env.APP_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Build native Docker and push to ghcr
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     file: HomeAssistant-Add-ons/alist-tvbox/Dockerfile-native
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-${{ env.APP_VERSION}}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # - name: Build host native Docker and push to ghcr
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     context: .
      #     file: HomeAssistant-Add-ons/alist-tvbox/Dockerfile-native-host
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-host,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-host-${{ env.APP_VERSION}}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
